# Generated by Django 4.2.5 on 2023-10-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_tasks_status_alter_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name_status',
            field=models.CharField(choices=[('waiting', 'В ожидании'), ('in_progress', 'В процессе'), ('completed', 'Завершена')], db_index=True, default='waiting', max_length=55),
        ),
    ]
